Write a for loop that will take the following numpy array:

[1, 4, 2,  
3, 9, 23,  
99, 4, 3] 

and:

- (a) print it out row by row 
- (b) print the sum of the elements on each row.
- (c) adapt your code so that instead of producing the sum of the elements in each row, it produces the sum of the elements in each column.

The output of the first part should be:

This is row 1 [1 4 2]  
This is row 2 [ 3  9 23]  
This is row 3 [99  4  3]  

The output of the second part should be:

The sum of [1 4 2] is 7  
The sum of [ 3  9 23] is 35  
The sum of [99  4  3] is 106  

The output of the third part should be:

The sum of [ 1  3 99] is 103  
The sum of [4 9 4] is 17  
The sum of [ 2 23  3] is 28  

Take the `for` loop you wrote for part (a) and use it as the body of a function called `print_rows()` which takes a numpy array (call it `my_array`) as a parameter and produces the same output as in part(a). You should call the function with `print_rows(my_array)` 

Re-write the `for` loop within the function as a `while` loop to produce the same output. Ensure that the while loop will run without error for an array of any number of rows.

In [1]:
import numpy as np

In [5]:
my_array = np.array([(1, 4, 2), (3, 9, 23), (99, 4, 3)])

In [6]:
my_array

array([[ 1,  4,  2],
       [ 3,  9, 23],
       [99,  4,  3]])

In [20]:
i = 1
for row in my_array:
    print("This is row", i, row)
    i += 1

This is row 1 [1 4 2]
This is row 2 [ 3  9 23]
This is row 3 [99  4  3]


In [16]:
for row in my_array:
    print("The sum of", row, "is", row[0] + row[1] + row[2])

The sum of [1 4 2] is 7
The sum of [ 3  9 23] is 35
The sum of [99  4  3] is 106


In [18]:
for column in my_array.T:
    print("The sum of", column, "is", column[0] + column[1] + column[2])

The sum of [ 1  3 99] is 103
The sum of [4 9 4] is 17
The sum of [ 2 23  3] is 28


In [19]:
my_array == my_array.T

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [22]:
def print_row(x):
    i = 1
    for row in x:
        print("This is row", i, row)
        i += 1

In [34]:
print_row(my_array)

[1 4 2]
[ 3  9 23]
[99  4  3]


In [33]:
def print_row(x):
    i = 0
    while i < len(my_array):
        print(my_array[i])
        i += 1

In [36]:
len(my_array)

3