In [1]:
import numpy as np

In [2]:
my_array = np.array([(1, 4, 2), (3, 9, 23), (99, 4, 3)])

In [3]:
my_array

array([[ 1,  4,  2],
       [ 3,  9, 23],
       [99,  4,  3]])

In [4]:
i = 1
for row in my_array:
    print("This is row", i, row)
    i +=1

This is row 1 [1 4 2]
This is row 2 [ 3  9 23]
This is row 3 [99  4  3]


In [5]:
for row in my_array:
    print("The sum of", row, "is", row[0] + row[1] + row[2])

The sum of [1 4 2] is 7
The sum of [ 3  9 23] is 35
The sum of [99  4  3] is 106


In [6]:
my_array.T

array([[ 1,  3, 99],
       [ 4,  9,  4],
       [ 2, 23,  3]])

In [7]:
for column in my_array.T:
    print("The sum of", column, "is", column[0] + column[1] + column[2])

The sum of [ 1  3 99] is 103
The sum of [4 9 4] is 17
The sum of [ 2 23  3] is 28


In [8]:
my_array.sum()

148

In [9]:
my_array.sum(axis=1)

array([  7,  35, 106])

In [10]:
my_array.sum(axis=0)

array([103,  17,  28])

In [11]:
def print_row(x):
    i = 1
    for row in x:
        print("This is row", i, row)
        i += 1

In [12]:
print_row(my_array)

This is row 1 [1 4 2]
This is row 2 [ 3  9 23]
This is row 3 [99  4  3]


In [13]:
def print_row(x):
    i = 0
    while i < len(x):
        print(x[i])
        i += 1

In [14]:
print_row(my_array)

[1 4 2]
[ 3  9 23]
[99  4  3]
